
---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "sno180-sriov-config"
  namespace: "ztp-site"
spec:
  bindingRules:
    sites: "sno180"
    version: "OCP-sriov"
  sourceFiles:
    - fileName: custom/LabelNode.yaml
      policyName: config
      metadata:
        name: sno180.workload.bos2.lab
        labels:
          node-role.kubernetes.io/standard: ""
