apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
#- sno163-4-18-worker.yaml
#- sno166-4-14-worker.yaml
#- sno167-4-12-worker.yaml
#- sno167-4-14-worker.yaml
#- sno167-4-16-worker.yaml
#- sno169-4-16-worker.yaml
#- sno180-4-14-worker.yaml
#- sno180-4-15-worker.yaml
#- sno180-4-16-worker.yaml
#- sno180-4-17-worker.yaml
#- sno180-4-18-worker.yaml
#- sno180-4-20-worker.yaml
#- sno183-4-16-worker.yaml
#- sno183-4-18-worker.yaml
#- sno183-4-19-worker.yaml
#- sno184-4-14-worker.yaml
#- sno184-4-18-worker.yaml
#- sno185-4-16-worker.yaml
#- sno185-4-18-worker.yaml
#- sno186-4-16-worker.yaml
- sno186-4-20-worker.yaml
#- sno187-4-16-worker.yaml
#- sno200-4-19-worker.yaml
#- example-sno.yaml
- compactcluster.yaml
#- compactcluster-hpe.yaml
#- sno180-4-18-worker-nmstate-nokia.yaml
- sno180-4-20-worker-sriov.yaml
